

/*
 * JDialogOperacionWarning.java
 *
 * Created on 02-sep-2011, 10:37:21
 */

package capaInterfaz;

/** Clase que gestiona el frame que se muestra al usuario como advertencia
 *  cuando se va ha realizar una operación especialmente delicada.
 *
 * @author Confiencial
 */
public class JDialogOperacionWarning extends javax.swing.JDialog {

    /** indica si el usuario ha confirmado o no que desea realizar la operación.
     */
    public static boolean operacionOK;

    /** Crea e inicializa un nuevo frame JDialogOperacionWarning
     *
     * @param parent frame padre.
     * @param modal indica si el frame es modal respecto al frame padre o no.
     */
    public JDialogOperacionWarning(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    } // fin del constructor

    /** Crea e inicializa un nuevo frame JDialogOperacionWarning
     *  Además, le asigna un texto al frame.
     *
     * @param parent frame padre.
     * @param message mensaje a mostrar.
     * @param modal indica si el frame es modal respecto al frame padre o no.
     */
    public JDialogOperacionWarning(java.awt.Frame parent, String message, boolean modal) {
        super(parent, modal);
        initComponents();
        jLabel1.setText(message);
        jLabel2.setText("");
    } // fin del constructor

    /** Crea e inicializa un nuevo frame JDialogOperacionWarning
     *  Además, le asigna un texto de 2 líneas al frame.
     *
     * @param parent frame padre.
     * @param message mensaje a mostrar.
     * @param message2 2º mensaje a mostrar.
     * @param modal indica si el frame es modal respecto al frame padre o no.
     */
    public JDialogOperacionWarning(java.awt.Frame parent, String message,
                                   String message2, boolean modal) {
        super(parent, modal);
        initComponents();
        jLabel1.setText(message);
        jLabel2.setText(message2);
    } // fin del constructor


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel imageLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonOK = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/capaInterfaz/images/advertencia1.png"))); // NOI18N

        jLabel1.setText("La operación se ha realizado con éxito.");

        jButtonOK.setText("Aceptar");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(imageLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jButtonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOK)
                    .addComponent(jButtonCancelar))
                .addGap(27, 27, 27))
            .addComponent(imageLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Método que captura el evento al pulsar el botón "Aceptar",
     *  asigna el valor TRUE al atributo operacionOK y cierra el frame.
     *
     * @param evt evento capturado.
     */
    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        operacionOK = true;
        dispose();
    }//GEN-LAST:event_jButtonOKActionPerformed

    /** Método que captura el evento al pulsar el botón "Cancelar" y
     *  asigna el valor FALSE al atributo operacionOK y cierra el frame.
     *
     * @param evt evento capturado.
     */
    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        operacionOK = false;
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

} // fin de la clase JDialogOperacionWarning