
/*
 * JDialogMenuSeleccionarBDD.java
 *
 * Created on 04-ago-2011, 11:28:28
 */

package capaInterfaz.menuConfiguracion;

import capaDatos.DataAccessObject;
import capaLogicaNegocio.Alumno;
import java.awt.Color;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import javax.swing.JLabel;



/** Clase que gestiona el Frame de selección y configuración de la Base de Datos
 *  del sistema cuando al iniciar la aplicación, ocurre algún error en la conexión.
 *
 * @author Confiencial
 */
public class JDialogMenuSeleccionarBDDPrimeraVez extends javax.swing.JDialog {

    /** Crea e inicializa un nuevo JDialogMenuSeleccionarBDDPrimeraVez.
     *
     * @param parent frame padre.
     * @param modal indica si el frame es modal respecto al frame padre o no.
     */
    public JDialogMenuSeleccionarBDDPrimeraVez(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jTextFieldURL.setText(DataAccessObject.URL);
        jTextFieldUser.setText(DataAccessObject.USER);
        jTextFieldPassword.setText(DataAccessObject.PASS);
        jLabelTestConnection.setText(" ");
        jLabelExplication = new JLabel();
        jLabelExplication.setBounds(20, 20, 300, 30);
        jLabelExplication.setText("Configure el acceso a la Base de Datos del sistema");
        this.add(jLabelExplication);
    } // fin del constructor

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jTextFieldURL = new javax.swing.JTextField();
        jTextFieldUser = new javax.swing.JTextField();
        jButtonTestConnection = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jButtonOK = new javax.swing.JButton();
        jTextFieldPassword = new javax.swing.JTextField();
        jLabelURL = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jLabelTestConnection = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextFieldURL.setText("Aqui poner por defecto la ruta actual");

        jTextFieldUser.setText("Y aqui la pass actual (con asteriscos)");

        jButtonTestConnection.setText("Comprobar");
        jButtonTestConnection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTestConnectionActionPerformed(evt);
            }
        });

        jButtonBack.setText("Cancelar");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jButtonOK.setText("Aceptar");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jTextFieldPassword.setText("jTextField3");
        jTextFieldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPasswordActionPerformed(evt);
            }
        });

        jLabelURL.setText("Ruta");

        jLabelUser.setText("Usuario");

        jLabelPassword.setText("Contraseña");

        jLabelTestConnection.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(305, Short.MAX_VALUE)
                        .addComponent(jButtonOK)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelURL, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabelPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                            .addComponent(jTextFieldUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                            .addComponent(jTextFieldURL, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))
                        .addGap(28, 28, 28)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonTestConnection, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonBack, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabelTestConnection, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelURL))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUser)
                    .addComponent(jButtonTestConnection))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jLabelTestConnection)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBack)
                    .addComponent(jButtonOK))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void jButtonTestConnectionActionPerformed(java.awt.event.ActionEvent evt) {
        Alumno alumno = new Alumno("X1770785S");

        String url = DataAccessObject.URL;
        String user = DataAccessObject.USER;
        String password = DataAccessObject.PASS;
        try {
            DataAccessObject.URL = jTextFieldURL.getText();
            DataAccessObject.USER = jTextFieldUser.getText();
            DataAccessObject.PASS = jTextFieldPassword.getText();

            jLabelTestConnection.setText(" ");
            boolean aux = alumno.estaDadoDeAlta();
            jLabelTestConnection.setText("Conexión establecida con éxito");
            jLabelTestConnection.setForeground(Color.green);

            DataAccessObject.URL = url;
            DataAccessObject.USER = user;
            DataAccessObject.PASS = password;
        } catch (RuntimeException e) {
            jLabelTestConnection.setText("Error al intentar establecer la conexión");
            jLabelTestConnection.setForeground(Color.red);
            DataAccessObject.URL = url;
            DataAccessObject.USER = user;
            DataAccessObject.PASS = password;
        }
    }

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
    }

    private void jTextFieldPasswordActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {
            DataAccessObject.URL = jTextFieldURL.getText();
            DataAccessObject.USER = jTextFieldUser.getText();
            DataAccessObject.PASS = jTextFieldPassword.getText();
        try {
            BufferedWriter escritor = new BufferedWriter(new  OutputStreamWriter(new FileOutputStream("./src/config/config.txt"),"UTF8"));
            String url, user, password;
            url = jTextFieldURL.getText();
            user = jTextFieldUser.getText();
            password = jTextFieldPassword.getText();
            escritor.write(url);
            escritor.newLine();
            escritor.write(user);
            escritor.newLine();
            escritor.write(password);
            escritor.close();
        } catch (FileNotFoundException e) {
            // TODO Auto-generated catch block
            System.out.println(e.getMessage());
            e.printStackTrace();
            throw new RuntimeException("Error al actualizar el archivo de configuración");
        } catch (IOException e1) {
            // TODO Auto-generated catch block
            System.out.println(e1.getMessage());
            e1.printStackTrace();
            throw new RuntimeException("Error al intentar acceder al archivo de configuración");
        }
        dispose();
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogMenuSeleccionarBDD dialog = new JDialogMenuSeleccionarBDD(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JButton jButtonTestConnection;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelTestConnection;
    private javax.swing.JLabel jLabelExplication;
    private javax.swing.JLabel jLabelURL;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JTextField jTextFieldPassword;
    private javax.swing.JTextField jTextFieldURL;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration

} // fin de la clase JDialogMenuSeleccionarBDDPrimeraVez